import type { Movie } from './models';

export const movieData: Movie[] = [
    {
        "id": 0,
        "title": "The Shawshank Redemption",
        "summary": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        "year": 1994,
        "poster": "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama"],
        "directors": ["Frank Darabont"],
        "actors": ["Tim Robbins", "Morgan Freeman"],
        "studio": {"name": "Shawshank Productions"},
    },
    {
        "id": 1,
        "title": "The Godfather",
        "summary": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his youngest and reluctant son.",
        "year": 1972,
        "poster": "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Crime", "Drama"],
        "directors": ["Francis Ford Coppola"],
        "actors": ["Marlon Brando", "Al Pacino"],
        "studio": {"name": "Paramount Pictures", "headquarters": "Hollywood, California, USA"},
    },
    {
        "id": 2,
        "title": "The Dark Knight",
        "summary": "When the menace known as the Joker wreaks havoc on Gotham, Batman must confront his greatest challenge.",
        "year": 2008,
        "poster": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
        "genres": ["Action", "Crime", "Drama"],
        "directors": ["Christopher Nolan"],
        "actors": ["Christian Bale", "Heath Ledger"],
        "studio": {"name": "Warner Bros.", "headquarters": "Burbank, California, USA"},
    },
    {
        "id": 3,
        "title": "Pulp Fiction",
        "summary": "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "year": 1994,
        "poster": "https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Crime", "Drama"],
        "directors": ["Quentin Tarantino"],
        "actors": ["John Travolta", "Samuel L. Jackson", "Uma Thurman"],
        "studio": {"name": "Miramax", "headquarters": "Los Angeles, California, USA"},      
    },
    {
        "id": 4,
        "title": "Forrest Gump",
        "summary": "The presidencies of Kennedy and Johnson, the Vietnam War, and the Watergate scandal unfold from the perspective of an Alabama man with an IQ of 75.",
        "year": 1994,
        "poster": "https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama", "Romance"],
        "directors": ["Robert Zemeckis"],
        "actors": ["Tom Hanks", "Sally Field"],
        "studio": {"name": "Paramount Pictures", "headquarters": "Hollywood, California, USA"},
    },
    {
        "id": 5,
        "title": "Inception",
        "summary": "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
        "year": 2010,
        "poster": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
        "genres": ["Action", "Sci-Fi", "Thriller"],
        "directors": ["Christopher Nolan"],
        "actors": ["Leonardo DiCaprio", "Marion Cotillard"],
        "studio": {"name": "Warner Bros.", "headquarters": "Burbank, California, USA"},
    },
    {
        "id": 6,
        "title": "The Matrix",
        "summary": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        "year": 1999,
        "poster": "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Action", "Sci-Fi"],
        "directors": ["Lana Wachowski", "Lilly Wachowski"],
        "actors": ["Keanu Reeves", "Laurence Fishburne"],
        "studio": {"name": "Warner Bros.", "headquarters": "Burbank, California, USA"},
    },
    {
        "id": 7,
        "title": "Interstellar",
        "summary": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        "year": 2014,
        "poster": "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Adventure", "Drama", "Sci-Fi"],
        "directors": ["Christopher Nolan"],
        "actors": ["Matthew McConaughey", "Anne Hathaway"],
        "studio": {"name": "Paramount Pictures"}
    },
    {
        "id": 8,
        "title": "The Avengers",
        "summary": "Earth's mightiest heroes must come together and learn to fight as a team to prevent an alien invasion.",
        "year": 2012,
        "poster": "https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": ["Joss Whedon"],
        "actors": ["Robert Downey Jr.", "Chris Evans"],
        "studio": {"name": "Marvel Studios"}
    },
    {
        "id": 9,
        "title": "Gladiator",
        "summary": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        "year": 2000,
        "poster": "https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Action", "Adventure", "Drama"],
        "directors": ["Ridley Scott"],
        "actors": ["Russell Crowe", "Joaquin Phoenix"],
        "studio": {"name": "Universal Pictures"}
    },
    {
        "id": 10,
        "title": "Titanic",
        "summary": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        "year": 1997,
        "poster": "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama", "Romance"],
        "directors": ["James Cameron"],
        "actors": ["Leonardo DiCaprio", "Kate Winslet"],
        "studio": {"name": "20th Century Studios"}
    },
    {
        "id": 11,
        "title": "Avatar",
        "summary": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
        "year": 2009,
        "poster": "https://m.media-amazon.com/images/M/MV5BMDEzMmQwZjctZWU2My00MWNlLWE0NjItMDJlYTRlNGJiZjcyXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Action", "Adventure", "Fantasy"],
        "directors": ["James Cameron"],
        "actors": ["Sam Worthington", "Zoe Saldana"],
        "studio": {"name": "20th Century Studios"}
    },
    {
        "id": 12,
        "title": "The Lion King",
        "summary": "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
        "year": 1994,
        "poster": "https://m.media-amazon.com/images/M/MV5BZGRiZDZhZjItM2M3ZC00Y2IyLTk3Y2MtMWY5YjliNDFkZTJlXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Animation", "Adventure", "Drama"],
        "directors": ["Roger Allers", "Rob Minkoff"],
        "actors": ["James Earl Jones", "Jeremy Irons"],
        "studio": {"name": "Walt Disney Animation"}
    },
    {
        "id": 13,
        "title": "Jurassic Park",
        "summary": "A pragmatic paleontologist tours an almost complete theme park is tasked with protecting a couple of kids.",
        "year": 1993,
        "poster": "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": ["Steven Spielberg"],
        "actors": ["Sam Neill", "Laura Dern"],
        "studio": {"name": "Universal Pictures"}
    },
    {
        "id": 14,
        "title": "Back to the Future",
        "summary": "A teenager is accidentally sent back in time in a time-traveling car invented by an eccentric scientist, and must ensure his parents fall in love.",
        "year": 1985,
        "poster": "https://m.media-amazon.com/images/M/MV5BZmM3ZjE0NzctNjBiOC00MDZmLTgzMTUtNGVlOWFlOTNiZDJiXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Adventure", "Comedy", "Sci-Fi"],
        "directors": ["Robert Zemeckis"],
        "actors": ["Michael J. Fox", "Christopher Lloyd"],
        "studio": {"name": "Universal Pictures"}
    },
    {
        "id": 15,
        "title": "Jaws",
        "summary": "When a huge shark begins terror on the beach, the police chief, an oceanographer, and a grizzled shark hunter embark on a mission to stop it.",
        "year": 1975,
        "poster": "https://m.media-amazon.com/images/M/MV5BYjViNDQzNmUtYzkxZi00NTk5LTljMmItYjJlZmZkODIxNjU1XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Adventure", "Thriller"],
        "directors": ["Steven Spielberg"],
        "actors": ["Roy Scheider", "Robert Shaw"],
        "studio": {"name": "Universal Pictures"}
    },
    {
        "id": 16,
        "title": "E.T. the Extra-Terrestrial",
        "summary": "A troubled child summons the courage to help a friendly alien escape Earth and return to his home planet.",
        "year": 1982,
        "poster": "https://m.media-amazon.com/images/M/MV5BYTNhNmY0YWMtMTczYi00MTA0LThhMmUtMTIxYzE0Y2QwMzRlXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Adventure", "Family", "Sci-Fi"],
        "directors": ["Steven Spielberg"],
        "actors": ["Henry Thomas", "Drew Barrymore"],
        "studio": {"name": "Universal Pictures"}
    },
    {
        "id": 17,
        "title": "The Silence of the Lambs",
        "summary": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
        "year": 1991,
        "poster": "https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Crime", "Drama", "Thriller"],
        "directors": ["Jonathan Demme"],
        "actors": ["Jodie Foster", "Anthony Hopkins"],
        "studio": {"name": "Orion Pictures"}
    },
    {
        "id": 18,
        "title": "Schindler's List",
        "summary": "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
        "year": 1993,
        "poster": "https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Biography", "Drama", "History"],
        "directors": ["Steven Spielberg"],
        "actors": ["Liam Neeson", "Ralph Fiennes"],
        "studio": {"name": "Universal Pictures"}
    },
    {
        "id": 19,
        "title": "The Shining",
        "summary": "A family isolated in a snowbound hotel descends into madness in this Stanley Kubrick masterpiece.",
        "year": 1980,
        "poster": "https://m.media-amazon.com/images/M/MV5BNmM5ZThhY2ItOGRjOS00NzZiLWEwYTItNDgyMjFkOTgxMmRiXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama", "Horror"],
        "directors": ["Stanley Kubrick"],
        "actors": ["Jack Nicholson", "Shelley Duvall"],
        "studio": {"name": "Warner Bros."}
    },
    {
        "id": 20,
        "title": "Casablanca",
        "summary": "In Casablanca, Morocco, an American expatriate meets a former lover, leading to a tense love triangle of epic proportions.",
        "year": 1942,
        "poster": "https://m.media-amazon.com/images/M/MV5BNWEzN2U1YTYtYTQyMS00NTVkLWE2NGQtZWFlMmM0MDNjMmRiXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama", "Romance", "War"],
        "directors": ["Michael Curtiz"],
        "actors": ["Humphrey Bogart", "Ingrid Bergman"],
        "studio": {"name": "Warner Bros."}
    },
    {
        "id": 21,
        "title": "Citizen Kane",
        "summary": "A reporter investigates the life of media mogul Charles Foster Kane from his rise to his mysterious death.",
        "year": 1941,
        "poster": "https://m.media-amazon.com/images/M/MV5BYjk1ZDJlMmUtOWQ0Zi00MDM5LTk1OGYtODczNjFmMGYwZGVkXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama", "Mystery"],
        "directors": ["Orson Welles"],
        "actors": ["Orson Welles", "Joseph Cotten"],
        "studio": {"name": "RKO Radio Pictures"}
    },
    {
        "id": 22,
        "title": "12 Angry Men",
        "summary": "A jury of twelve must deliberate and reach a unanimous verdict in a murder case.",
        "year": 1957,
        "poster": "https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Crime", "Drama"],
        "directors": ["Sidney Lumet"],
        "actors": ["Henry Fonda", "Lee J. Cobb"],
        "studio": {"name": "MGM"}
    },
    {
        "id": 23,
        "title": "Singin' in the Rain",
        "summary": "Three friends make it big in silent films and must transition to talking pictures.",
        "year": 1952,
        "poster": "https://m.media-amazon.com/images/M/MV5BMGQzZDFjZWUtZDU4ZS00ZjM3LTgyYmItYjA3YmIwYzRkZWY3XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Comedy", "Musical", "Romance"],
        "directors": ["Gene Kelly", "Stanley Donen"],
        "actors": ["Gene Kelly", "Donald O'Connor"],
        "studio": {"name": "MGM"}
    },
    {
        "id": 24,
        "title": "Vertigo",
        "summary": "A former policeman is hired to follow a mysterious woman in San Francisco and things take a dark turn.",
        "year": 1958,
        "poster": "https://m.media-amazon.com/images/M/MV5BNzEyZTUxMWItMGVhYy00Y2NlLTljYTMtYzBmMzI1YmUyMDBkXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Mystery", "Thriller"],
        "directors": ["Alfred Hitchcock"],
        "actors": ["James Stewart", "Kim Novak"],
        "studio": {"name": "Paramount Pictures"}
    },
    {
        "id": 25,
        "title": "Psycho",
        "summary": "A woman is murdered after checking into an eerie motel run by a disturbed young man.",
        "year": 1960,
        "poster": "https://m.media-amazon.com/images/M/MV5BYjZhMzFiZjItODA3ZC00MmRhLWIzMGYtMmVjOWUwYTA3MTRjXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Horror", "Mystery", "Thriller"],
        "directors": ["Alfred Hitchcock"],
        "actors": ["Anthony Perkins", "Janet Leigh"],
        "studio": {"name": "Paramount Pictures"}
    },
    {
        "id": 26,
        "title": "Rear Window",
        "summary": "A housebound photographer observes the lives of his neighbors from his window and suspects one of them of murder.",
        "year": 1954,
        "poster": "https://m.media-amazon.com/images/M/MV5BODZhOWI1ODgtMzdiOS00YjNkLTgwOGUtYmIyZDg5ZmQwMzQ1XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Mystery", "Thriller"],
        "directors": ["Alfred Hitchcock"],
        "actors": ["James Stewart", "Grace Kelly"],
        "studio": {"name": "Paramount Pictures"}
    },
    {
        "id": 27,
        "title": "Goodfellas",
        "summary": "The story of Henry Hill and his life in the mafia, covering his relationship with his wife and his partners.",
        "year": 1990,
        "poster": "https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Crime", "Drama"],
        "directors": ["Martin Scorsese"],
        "actors": ["Ray Liotta", "Robert De Niro"],
        "studio": {"name": "Legendary Pictures"}
    },
    {
        "id": 28,
        "title": "The Godfather Part II",
        "summary": "The early life and career of Vito Corleone in 1920s New York is portrayed while his youngest son Michael expands his crime empire.",
        "year": 1974,
        "poster": "https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Crime", "Drama"],
        "directors": ["Francis Ford Coppola"],
        "actors": ["Al Pacino", "Robert De Niro"],
        "studio": {"name": "Paramount Pictures"}
    },
    {
        "id": 29,
        "title": "Apocalypse Now",
        "summary": "A captain is sent upriver to assess a mysterious commander who has disappeared.",
        "year": 1979,
        "poster": "https://m.media-amazon.com/images/M/MV5BZDhiMTljYjYtODc1Yy00MmEwLTg2OTYtYmE1YTRmNDE4MmEwXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama", "War"],
        "directors": ["Francis Ford Coppola"],
        "actors": ["Martin Sheen", "Marlon Brando"],
        "studio": {"name": "Legendary Pictures"}
    },
    {
        "id": 30,
        "title": "Se7en",
        "summary": "Two detectives hunt a serial killer who uses the seven deadly sins as his motives.",
        "year": 1995,
        "poster": "https://m.media-amazon.com/images/M/MV5BY2IzNzMxZjctZjUxZi00YzAxLTk3ZjMtODFjODdhMDU5NDM1XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Crime", "Drama", "Mystery"],
        "directors": ["David Fincher"],
        "actors": ["Brad Pitt", "Morgan Freeman"],
        "studio": {"name": "Miramax"}
    },
    {
        "id": 31,
        "title": "The Usual Suspects",
        "summary": "A con artist is arrested alongside other criminals and tells the story of how they came together.",
        "year": 1995,
        "poster": "https://m.media-amazon.com/images/M/MV5BOTE5MDUxZDUtZWZmZC00NDVmLWFhOGQtNWI2YTc4NzY3MGQ0XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Crime", "Drama", "Mystery"],
        "directors": ["Bryan Singer"],
        "actors": ["Gabriel Byrne", "Kevin Spacey"],
        "studio": {"name": "New Line Cinema"}
    },
    {
        "id": 32,
        "title": "Saving Private Ryan",
        "summary": "Following the Normandy Landings, a group of men are tasked with finding and bringing home Private James Ryan.",
        "year": 1998,
        "poster": "https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama", "War"],
        "directors": ["Steven Spielberg"],
        "actors": ["Tom Hanks", "Edward Burns"],
        "studio": {"name": "Universal Pictures"}
    },
    {
        "id": 33,
        "title": "The Green Mile",
        "summary": "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape.",
        "year": 1999,
        "poster": "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg",
        "genres": ["Crime", "Drama", "Fantasy"],
        "directors": ["Frank Darabont"],
        "actors": ["Tom Hanks", "Michael Clarke Duncan"],
        "studio": {"name": "Orion Pictures"}
    },
    {
        "id": 34,
        "title": "Dances with Wolves",
        "summary": "A Union soldier befriends a Native American tribe and is accepted into their community.",
        "year": 1990,
        "poster": "https://m.media-amazon.com/images/M/MV5BMTY3OTI5NDczN15BMl5BanBnXkFtZTcwNDA0NDY3Mw@@._V1_SX300.jpg",
        "genres": ["Adventure", "Drama", "Western"],
        "directors": ["Kevin Costner"],
        "actors": ["Kevin Costner", "Mary McDonnell"],
        "studio": {"name": "Castle Rock Entertainment"}
    },
    {
        "id": 35,
        "title": "Braveheart",
        "summary": "Scottish warrior William Wallace leads his countrymen in a rebellion to free Scotland from English rule.",
        "year": 1995,
        "poster": "https://m.media-amazon.com/images/M/MV5BNGMxZDBhNGQtYTZlNi00N2UzLWI4NDEtNmUzNWM2NTdmZDA0XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Biography", "Drama", "History"],
        "directors": ["Mel Gibson"],
        "actors": ["Mel Gibson", "Sophie Marceau"],
        "studio": {"name": "Castle Rock Entertainment"}
    },
    {
        "id": 36,
        "title": "The Departed",
        "summary": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang.",
        "year": 2006,
        "poster": "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg",
        "genres": ["Crime", "Drama", "Thriller"],
        "directors": ["Martin Scorsese"],
        "actors": ["Leonardo DiCaprio", "Matt Damon"],
        "studio": {"name": "Legendary Pictures"}
    },
    {
        "id": 37,
        "title": "Gladiator II",
        "summary": "Years after witnessing his father's death, Lucius faces his past when confronted by new powerful forces.",
        "year": 2024,
        "poster": "https://m.media-amazon.com/images/M/MV5BMWYzZTM5ZGQtOGE5My00NmM2LWFlMDEtMGNjYjdmOWM1MzA1XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Action", "Adventure", "Drama"],
        "directors": ["Ridley Scott"],
        "actors": ["Paul Mescal", "Pedro Pascal"],
        "studio": {"name": "Universal Pictures"}
    },
    {
        "id": 38,
        "title": "Oppenheimer",
        "summary": "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
        "year": 2023,
        "poster": "https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTJmNTM5MjVmYTQ4XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Biography", "Drama", "History"],
        "directors": ["Christopher Nolan"],
        "actors": ["Cillian Murphy", "Robert Downey Jr."],
        "studio": {"name": "Warner Bros."}
    },
    {
        "id": 39,
        "title": "Barbie",
        "summary": "Barbie's perfect life in the Barbie universe is interrupted when she gets a chance to experience the real world.",
        "year": 2023,
        "poster": "https://m.media-amazon.com/images/M/MV5BYjI3NDU0ZGYtYjA2YS00Y2RlLTgwZDAtYTE2YTM5ZjE1M2JlXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Adventure", "Comedy", "Fantasy"],
        "directors": ["Greta Gerwig"],
        "actors": ["Margot Robbie", "Ryan Gosling"],
        "studio": {"name": "Dreamworks Pictures"}
    },
    {
        "id": 40,
        "title": "Killers of the Flower Moon",
        "summary": "Oil brings riches and violence to the Osage Nation, when a series of murders plagues the community.",
        "year": 2023,
        "poster": "https://m.media-amazon.com/images/M/MV5BZWY5ZDVjNTUtODI5Yy00MjFhLWEyM2EtYzZjM2VjZTI0MTBjXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Crime", "Drama", "History"],
        "directors": ["Martin Scorsese"],
        "actors": ["Leonardo DiCaprio", "Robert De Niro"],
        "studio": {"name": "Legendary Pictures"}
    },
    {
        "id": 42,
        "title": "Dune",
        "summary": "Paul Atreides travels to the dangerous planet Arrakis to ensure the future of his family and people.",
        "year": 2021,
        "poster": "https://m.media-amazon.com/images/M/MV5BNWIyNmU5MGYtZDZmNi00ZjAwLWJlYjgtZTc0ZGIxMDE4ZGYwXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Action", "Adventure", "Drama"],
        "directors": ["Denis Villeneuve"],
        "actors": ["Timothée Chalamet", "Zendaya"],
        "studio": {"name": "Warner Bros."}
    },
    {
        "id": 43,
        "title": "Dune: Part Two",
        "summary": "Paul Atreides must travel to the dangerous planet Arrakis to teach the Fremen the ways of fighting Harkonnen oppressors.",
        "year": 2024,
        "poster": "https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWUyZGJhXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Action", "Adventure", "Drama"],
        "directors": ["Denis Villeneuve"],
        "actors": ["Timothée Chalamet", "Zendaya"],
        "studio": {"name": "Warner Bros."}
    },
    {
        "id": 44,
        "title": "Twisters",
        "summary": "A former storm chaser reluctantly joins forces with a new team to battle destructive tornadoes.",
        "year": 2024,
        "poster": "https://m.media-amazon.com/images/M/MV5BNjM4MWEwMTEtNTcwYi00ZDI4LWEwMzUtNDMzODBhZmI5MWE1XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Action", "Adventure", "Drama"],
        "directors": ["Lee Isaac Chung"],
        "actors": ["Daisy Edgar-Jones", "Glen Powell"],
        "studio": {"name": "Universal Pictures"}
    },
    {
        "id": 45,
        "title": "Inside Out 2",
        "summary": "Riley's emotions are joined by new feelings as she enters her teenage years and navigates new social challenges.",
        "year": 2024,
        "poster": "https://m.media-amazon.com/images/M/MV5BYWY3MDE2Y2UtOTE3Zi00MGUzLTg2MTItZjE1ZWVkMGVlODRmXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Animation", "Adventure", "Comedy"],
        "directors": ["Kelsey Mann"],
        "actors": ["Kensington Tallman", "Tony Hawk"],
        "studio": {"name": "Walt Disney Animation"}
    },
    {
        "id": 46,
        "title": "Deadpool & Wolverine",
        "summary": "Merc with a Mouth teams up with Wolverine for an adventure across the multiverse.",
        "year": 2024,
        "poster": "https://m.media-amazon.com/images/M/MV5BZTk5ODY0MmQtMzA3Ni00NGY1LThiYzItZThiNjFiNDM4MTM3XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Action", "Comedy", "Sci-Fi"],
        "directors": ["Shawn Levy"],
        "actors": ["Ryan Reynolds", "Hugh Jackman"],
        "studio": {"name": "Marvel Studios"}
    },
    {
        "id": 47,
        "title": "A Quiet Place: Day One",
        "summary": "As New York City is invaded by alien creatures that hunt by sound, a woman struggles to find her way through the chaos.",
        "year": 2024,
        "poster": "https://m.media-amazon.com/images/M/MV5BMDdjZTljZWMtMDIwNi00MTA5LTkxZmItNmY0NDA3ZDM0N2M2XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama", "Horror", "Sci-Fi"],
        "directors": ["Michael Sarnoski"],
        "actors": ["Lupita Nyong'o", "Joseph Quinn"],
        "studio": {"name": "Paramount Pictures"}
    },
    {
        "id": 48,
        "title": "The Sympathizer",
        "summary": "A conflicted spy navigates double life in post-war Vietnam during a pivotal era of American-Vietnamese relations.",
        "year": 2024,
        "poster": "https://m.media-amazon.com/images/M/MV5BZDI2MGYzYWMtZjVlNS00N2JlLTg0OTQtZWU3MDY5MmViYTg5XkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama", "History", "Thriller"],
        "directors": ["Park Chan-wook"],
        "actors": ["Hal Yamanouchi", "Robert Downey Jr."],
        "studio": {"name": "Apple TV+"}
    },
    {
        "id": 50,
        "title": "The Last Duel",
        "summary": "A knight returns from war to find his wife has accused his closest friend of rape, leading to a final duel.",
        "year": 2021,
        "poster": "https://m.media-amazon.com/images/M/MV5BZGZiNDFkNDgtNDlmNS00NzZmLTg4MmItMzJkYjdmMjJkZDliXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama", "History"],
        "directors": ["Ridley Scott"],
        "actors": ["Matt Damon", "Adam Driver"],
        "studio": {"name": "Universal Pictures"}
    },
    {
        "id": 51,
        "title": "Nomadland",
        "summary": "A woman in her sixties loses everything in the Great Recession and decides to live as a van-dwelling nomad.",
        "year": 2020,
        "poster": "https://m.media-amazon.com/images/M/MV5BZGNkOWQ0ZjMtMTc4Ny00NDRhLTgyMjUtNzFmZDM0MTc3N2JjXkEyXkFqcGc@._V1_SX300.jpg",
        "genres": ["Drama"],
        "directors": ["Chloé Zhao"],
        "actors": ["Frances McDormand"],
        "studio": {"name": "Searchlight Pictures"}
    },
]