directors = [
  {'id': 0, 'name': 'Steven Spielberg'}, 
  {'id': 1, 'name': 'Chloé Zhao'}, 
  {'id': 2, 'name': 'James Cameron'}, 
  {'id': 3, 'name': 'David Fincher'}, 
  {'id': 4, 'name': 'Lana Wachowski'}, 
  {'id': 5, 'name': 'Frank Darabont'}, 
  {'id': 6, 'name': 'Martin Scorsese'}, 
  {'id': 7, 'name': 'Kelsey Mann'}, 
  {'id': 8, 'name': 'Jonathan Demme'}, 
  {'id': 9, 'name': 'Park Chan-wook'}, 
  {'id': 10, 'name': 'Robert Zemeckis'}, 
  {'id': 11, 'name': 'Michael Sarnoski'}, 
  {'id': 12, 'name': 'Brady Corbet'}, 
  {'id': 13, 'name': 'Rob Minkoff'}, 
  {'id': 14, 'name': 'Joss Whedon'}, 
  {'id': 15, 'name': 'Christopher Nolan'}, 
  {'id': 16, 'name': 'Stanley Kubrick'}, 
  {'id': 17, 'name': 'Roger Allers'}, 
  {'id': 18, 'name': 'Alfred Hitchcock'}, 
  {'id': 19, 'name': 'Orson Welles'}, 
  {'id': 20, 'name': 'Tech Filmmaker'}, 
  {'id': 21, 'name': 'Lee Isaac Chung'}, 
  {'id': 22, 'name': 'Gene Kelly'}, 
  {'id': 23, 'name': 'Stanley Donen'}, 
  {'id': 24, 'name': 'Bryan Singer'}, 
  {'id': 25, 'name': 'Greta Gerwig'}, 
  {'id': 26, 'name': 'Lilly Wachowski'}, 
  {'id': 27, 'name': 'Sidney Lumet'}, 
  {'id': 28, 'name': 'Ridley Scott'}, 
  {'id': 29, 'name': 'Michael Curtiz'}, 
  {'id': 30, 'name': 'Francis Ford Coppola'}, 
  {'id': 31, 'name': 'Denis Villeneuve'}, 
  {'id': 32, 'name': 'Mel Gibson'}, 
  {'id': 33, 'name': 'Shawn Levy'}, 
  {'id': 34, 'name': 'Quentin Tarantino'}, 
  {'id': 35, 'name': 'Kevin Costner'}
]

genres = [
  {'id': 0, 'name': 'Animation'}, 
  {'id': 1, 'name': 'Crime'}, 
  {'id': 2, 'name': 'Romance'}, 
  {'id': 3, 'name': 'Thriller'}, 
  {'id': 4, 'name': 'Horror'}, 
  {'id': 5, 'name': 'History'}, 
  {'id': 6, 'name': 'Adventure'}, 
  {'id': 7, 'name': 'Sci-Fi'}, 
  {'id': 8, 'name': 'Musical'}, 
  {'id': 9, 'name': 'Biography'}, 
  {'id': 10, 'name': 'Comedy'}, 
  {'id': 11, 'name': 'War'}, 
  {'id': 12, 'name': 'Action'}, 
  {'id': 13, 'name': 'Mystery'}, 
  {'id': 14, 'name': 'Western'}, 
  {'id': 15, 'name': 'Fantasy'}, 
  {'id': 16, 'name': 'Family'}, 
  {'id': 17, 'name': 'Documentary'}, 
  {'id': 18, 'name': 'Drama'}
]

actors = [
  {'id': 0, 'name': 'Anne Hathaway'}, 
  {'id': 1, 'name': 'Frances McDormand'}, 
  {'id': 2, 'name': 'Joseph Cotten'}, 
  {'id': 3, 'name': 'James Stewart'}, 
  {'id': 4, 'name': 'Al Pacino'}, 
  {'id': 5, 'name': "Lupita Nyong'o"}, 
  {'id': 6, 'name': 'Henry Fonda'}, 
  {'id': 7, 'name': 'Ingrid Bergman'}, 
  {'id': 8, 'name': 'James Earl Jones'}, 
  {'id': 9, 'name': 'Michael J. Fox'}, 
  {'id': 10, 'name': 'Russell Crowe'}, 
  {'id': 11, 'name': 'Shelley Duvall'}, 
  {'id': 12, 'name': 'Kim Novak'}, 
  {'id': 13, 'name': 'Sophie Marceau'}, 
  {'id': 14, 'name': 'Morgan Freeman'}, 
  {'id': 15, 'name': 'Robert De Niro'}, 
  {'id': 16, 'name': 'Leonardo DiCaprio'}, 
  {'id': 17, 'name': 'Ray Liotta'}, 
  {'id': 18, 'name': 'Heath Ledger'}, 
  {'id': 19, 'name': 'Timothée Chalamet'}, 
  {'id': 20, 'name': 'Tom Hanks'}, 
  {'id': 21, 'name': 'Keanu Reeves'}, 
  {'id': 22, 'name': 'Matt Damon'}, 
  {'id': 23, 'name': 'Zendaya'}, 
  {'id': 24, 'name': 'Adrien Brody'}, 
  {'id': 25, 'name': 'Lee J. Cobb'}, 
  {'id': 26, 'name': 'Uma Thurman'}, 
  {'id': 27, 'name': 'Margot Robbie'}, 
  {'id': 28, 'name': 'Robert Shaw'}, 
  {'id': 29, 'name': 'Brad Pitt'}, 
  {'id': 30, 'name': 'Kate Winslet'}, 
  {'id': 31, 'name': 'Kevin Spacey'}, 
  {'id': 32, 'name': 'Christopher Lloyd'}, 
  {'id': 33, 'name': 'John Travolta'}, 
  {'id': 34, 'name': 'Orson Welles'}, 
  {'id': 35, 'name': 'Michael Clarke Duncan'}, 
  {'id': 36, 'name': 'Robert Downey Jr.'}, 
  {'id': 37, 'name': 'Jeremy Irons'}, 
  {'id': 38, 'name': 'Janet Leigh'}, 
  {'id': 39, 'name': 'Henry Thomas'}, 
  {'id': 40, 'name': 'Grace Kelly'}, 
  {'id': 41, 'name': 'Sam Neill'}, 
  {'id': 42, 'name': 'Roy Scheider'}, 
  {'id': 43, 'name': 'Hal Yamanouchi'}, 
  {'id': 44, 'name': 'Paul Mescal'}, 
  {'id': 45, 'name': 'Ryan Gosling'}, 
  {'id': 46, 'name': 'Drew Barrymore'}, 
  {'id': 47, 'name': 'Tony Hawk'}, 
  {'id': 48, 'name': 'Jodie Foster'}, 
  {'id': 49, 'name': 'Gabriel Byrne'}, 
  {'id': 50, 'name': 'Hugh Jackman'}, 
  {'id': 51, 'name': 'Various Experts'}, 
  {'id': 52, 'name': 'Samuel L. Jackson'}, 
  {'id': 53, 'name': 'Marlon Brando'}, 
  {'id': 54, 'name': 'Gene Kelly'}, 
  {'id': 55, 'name': 'Adam Driver'}, 
  {'id': 56, 'name': 'Edward Burns'}, 
  {'id': 57, 'name': 'Liam Neeson'}, 
  {'id': 58, 'name': 'Cillian Murphy'}, 
  {'id': 59, 'name': 'Mel Gibson'}, 
  {'id': 60, 'name': 'Daisy Edgar-Jones'}, 
  {'id': 61, 'name': 'Humphrey Bogart'}, 
  {'id': 62, 'name': 'Zoe Saldana'}, 
  {'id': 63, 'name': 'Kevin Costner'}, 
  {'id': 64, 'name': 'Jack Nicholson'}, 
  {'id': 65, 'name': 'Christian Bale'}, 
  {'id': 66, 'name': 'Sally Field'}, 
  {'id': 67, 'name': 'Chris Evans'}, 
  {'id': 68, 'name': 'Ryan Reynolds'}, 
  {'id': 69, 'name': 'Marion Cotillard'}, 
  {'id': 70, 'name': 'Joaquin Phoenix'}, 
  {'id': 71, 'name': 'Laura Dern'}, 
  {'id': 72, 'name': 'Joseph Quinn'}, 
  {'id': 73, 'name': 'Ralph Fiennes'}, 
  {'id': 74, 'name': "Donald O'Connor"}, 
  {'id': 75, 'name': 'Pedro Pascal'}, 
  {'id': 76, 'name': 'Kensington Tallman'}, 
  {'id': 77, 'name': 'Tim Robbins'}, 
  {'id': 78, 'name': 'Glen Powell'}, 
  {'id': 79, 'name': 'Mary McDonnell'}, 
  {'id': 80, 'name': 'Matthew McConaughey'}, 
  {'id': 81, 'name': 'Sam Worthington'}, 
  {'id': 82, 'name': 'Anthony Perkins'}, 
  {'id': 83, 'name': 'Anthony Hopkins'}, 
  {'id': 84, 'name': 'Guy Pearce'}, 
  {'id': 85, 'name': 'Martin Sheen'}, 
  {'id': 86, 'name': 'Laurence Fishburne'}
]

studios = [
  {'id': 0, 'name': 'Shawshank Productions', 'headquarters': 'New York, USA'},
  {'id': 1, 'name': 'Paramount Pictures', 'headquarters': 'Los Angeles, USA'},
  {'id': 2, 'name': 'Warner Bros.', 'headquarters': 'Burbank, USA'},
  {'id': 3, 'name': 'Miramax', 'headquarters': 'Los Angeles, USA'},
  {'id': 4, 'name': 'Legendary Pictures', 'headquarters': 'Burbank, USA'},
  {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'},
  {'id': 6, 'name': 'Marvel Studios', 'headquarters': 'Los Angeles, USA'},
  {'id': 7, 'name': 'Dreamworks Pictures', 'headquarters': 'Glendale, USA'},
  {'id': 8, 'name': '20th Century Studios', 'headquarters': 'Los Angeles, USA'},
  {'id': 9, 'name': 'Walt Disney Animation', 'headquarters': 'Burbank, USA'},
  {'id': 10, 'name': 'Orion Pictures', 'headquarters': 'Los Angeles, USA'},
  {'id': 11, 'name': 'RKO Radio Pictures', 'headquarters': 'New York, USA'},
  {'id': 12, 'name': 'MGM', 'headquarters': 'Los Angeles, USA'},
  {'id': 13, 'name': 'New Line Cinema', 'headquarters': 'Burbank, USA'},
  {'id': 14, 'name': 'Castle Rock Entertainment', 'headquarters': 'Burbank, USA'},
  {'id': 15, 'name': 'Apple TV+', 'headquarters': 'Cupertino, USA'},
  {'id': 16, 'name': 'Searchlight Pictures', 'headquarters': 'Los Angeles, USA'},
  {'id': 17, 'name': 'Pixar Animation', 'headquarters': 'Emeryville, USA'},
  {'id': 18, 'name': 'A24', 'headquarters': 'New York, USA'},
  {'id': 19, 'name': 'Tech Education Inc.', 'headquarters': 'San Francisco, USA'}
]

movies = [
  {'id': 0, 'title': 'The Shawshank Redemption', 'summary': 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'year': 1994, 'genres': [{'id': 18, 'name': 'Drama'}], 'directors': [{'id': 5, 'name': 'Frank Darabont'}], 'actors': [{'id': 14, 'name': 'Morgan Freeman'}, {'id': 77, 'name': 'Tim Robbins'}], 'studio': {'id': 0, 'name': 'Shawshank Productions', 'headquarters': 'New York, USA'}}, 
  {'id': 1, 'title': 'The Godfather', 'summary': 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his youngest and reluctant son.', 'year': 1972, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 30, 'name': 'Francis Ford Coppola'}], 'actors': [{'id': 4, 'name': 'Al Pacino'}, {'id': 53, 'name': 'Marlon Brando'}], 'studio': {'id': 1, 'name': 'Paramount Pictures', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 2, 'title': 'The Dark Knight', 'summary': 'When the menace known as the Joker wreaks havoc on Gotham, Batman must confront his greatest challenge.', 'year': 2008, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 12, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 15, 'name': 'Christopher Nolan'}], 'actors': [{'id': 18, 'name': 'Heath Ledger'}, {'id': 65, 'name': 'Christian Bale'}], 'studio': {'id': 2, 'name': 'Warner Bros.', 'headquarters': 'Burbank, USA'}},
  {'id': 3, 'title': 'Pulp Fiction', 'summary': "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", 'year': 1994, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 34, 'name': 'Quentin Tarantino'}], 'actors': [{'id': 26, 'name': 'Uma Thurman'}, {'id': 33, 'name': 'John Travolta'}, {'id': 52, 'name': 'Samuel L. Jackson'}], 'studio': {'id': 3, 'name': 'Miramax', 'headquarters': 'Los Angeles, USA'}},
  {'id': 4, 'title': 'Forrest Gump', 'summary': 'The presidencies of Kennedy and Johnson, the Vietnam War, and the Watergate scandal unfold from the perspective of an Alabama man with an IQ of 75.', 'year': 1994, 'genres': [{'id': 2, 'name': 'Romance'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 10, 'name': 'Robert Zemeckis'}], 'actors': [{'id': 20, 'name': 'Tom Hanks'}, {'id': 66, 'name': 'Sally Field'}], 'studio': {'id': 1, 'name': 'Paramount Pictures', 'headquarters': 'Los Angeles, USA'}},
  {'id': 5, 'title': 'Inception', 'summary': 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.', 'year': 2010, 'genres': [{'id': 3, 'name': 'Thriller'}, {'id': 7, 'name': 'Sci-Fi'}, {'id': 12, 'name': 'Action'}], 'directors': [{'id': 15, 'name': 'Christopher Nolan'}], 'actors': [{'id': 16, 'name': 'Leonardo DiCaprio'}, {'id': 69, 'name': 'Marion Cotillard'}], 'studio': {'id': 2, 'name': 'Warner Bros.', 'headquarters': 'Burbank, USA'}},
  {'id': 6, 'title': 'The Matrix', 'summary': 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 'year': 1999, 'genres': [{'id': 7, 'name': 'Sci-Fi'}, {'id': 12, 'name': 'Action'}], 'directors': [{'id': 4, 'name': 'Lana Wachowski'}, {'id': 26, 'name': 'Lilly Wachowski'}], 'actors': [{'id': 21, 'name': 'Keanu Reeves'}, {'id': 86, 'name': 'Laurence Fishburne'}], 'studio': {'id': 2, 'name': 'Warner Bros.', 'headquarters': 'Burbank, USA'}},
  {'id': 7, 'title': 'Interstellar', 'summary': "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", 'year': 2014, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 7, 'name': 'Sci-Fi'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 15, 'name': 'Christopher Nolan'}], 'actors': [{'id': 0, 'name': 'Anne Hathaway'}, {'id': 80, 'name': 'Matthew McConaughey'}], 'studio': {'id': 1, 'name': 'Paramount Pictures', 'headquarters': 'Los Angeles, USA'}},
  {'id': 8, 'title': 'The Avengers', 'summary': "Earth's mightiest heroes must come together and learn to fight as a team to prevent an alien invasion.", 'year': 2012, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 7, 'name': 'Sci-Fi'}, {'id': 12, 'name': 'Action'}], 'directors': [{'id': 14, 'name': 'Joss Whedon'}], 'actors': [{'id': 36, 'name': 'Robert Downey Jr.'}, {'id': 67, 'name': 'Chris Evans'}], 'studio': {'id': 6, 'name': 'Marvel Studios', 'headquarters': 'Los Angeles, USA'}},
  {'id': 9, 'title': 'Gladiator', 'summary': 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 'year': 2000, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 12, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 28, 'name': 'Ridley Scott'}], 'actors': [{'id': 10, 'name': 'Russell Crowe'}, {'id': 70, 'name': 'Joaquin Phoenix'}], 'studio': {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'}}, 
  {'id': 10, 'title': 'Titanic', 'summary': 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', 'year': 1997, 'genres': [{'id': 2, 'name': 'Romance'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 2, 'name': 'James Cameron'}], 'actors': [{'id': 16, 'name': 'Leonardo DiCaprio'}, {'id': 30, 'name': 'Kate Winslet'}], 'studio': {'id': 8, 'name': '20th Century Studios', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 11, 'title': 'Avatar', 'summary': 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.', 'year': 2009, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 12, 'name': 'Action'}, {'id': 15, 'name': 'Fantasy'}], 'directors': [{'id': 2, 'name': 'James Cameron'}], 'actors': [{'id': 62, 'name': 'Zoe Saldana'}, {'id': 81, 'name': 'Sam Worthington'}], 'studio': {'id': 8, 'name': '20th Century Studios', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 12, 'title': 'The Lion King', 'summary': 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 'year': 1994, 'genres': [{'id': 0, 'name': 'Animation'}, {'id': 6, 'name': 'Adventure'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 13, 'name': 'Rob Minkoff'}, {'id': 17, 'name': 'Roger Allers'}], 'actors': [{'id': 8, 'name': 'James Earl Jones'}, {'id': 37, 'name': 'Jeremy Irons'}], 'studio': {'id': 9, 'name': 'Walt Disney Animation', 'headquarters': 'Burbank, USA'}}, 
  {'id': 13, 'title': 'Jurassic Park', 'summary': 'A pragmatic paleontologist tours an almost complete theme park is tasked with protecting a couple of kids.', 'year': 1993, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 7, 'name': 'Sci-Fi'}, {'id': 12, 'name': 'Action'}], 'directors': [{'id': 0, 'name': 'Steven Spielberg'}], 'actors': [{'id': 41, 'name': 'Sam Neill'}, {'id': 71, 'name': 'Laura Dern'}], 'studio': {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'}}, 
  {'id': 14, 'title': 'Back to the Future', 'summary': 'A teenager is accidentally sent back in time in a time-traveling car invented by an eccentric scientist, and must ensure his parents fall in love.', 'year': 1985, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 7, 'name': 'Sci-Fi'}, {'id': 10, 'name': 'Comedy'}], 'directors': [{'id': 10, 'name': 'Robert Zemeckis'}], 'actors': [{'id': 9, 'name': 'Michael J. Fox'}, {'id': 32, 'name': 'Christopher Lloyd'}], 'studio': {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'}}, 
  {'id': 15, 'title': 'Jaws', 'summary': 'When a huge shark begins terror on the beach, the police chief, an oceanographer, and a grizzled shark hunter embark on a mission to stop it.', 'year': 1975, 'genres': [{'id': 3, 'name': 'Thriller'}, {'id': 6, 'name': 'Adventure'}], 'directors': [{'id': 0, 'name': 'Steven Spielberg'}], 'actors': [{'id': 28, 'name': 'Robert Shaw'}, {'id': 42, 'name': 'Roy Scheider'}], 'studio': {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'}}, 
  {'id': 16, 'title': 'E.T. the Extra-Terrestrial', 'summary': 'A troubled child summons the courage to help a friendly alien escape Earth and return to his home planet.', 'year': 1982, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 7, 'name': 'Sci-Fi'}, {'id': 16, 'name': 'Family'}], 'directors': [{'id': 0, 'name': 'Steven Spielberg'}], 'actors': [{'id': 39, 'name': 'Henry Thomas'}, {'id': 46, 'name': 'Drew Barrymore'}], 'studio': {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'}}, 
  {'id': 17, 'title': 'The Silence of the Lambs', 'summary': 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.', 'year': 1991, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 3, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 8, 'name': 'Jonathan Demme'}], 'actors': [{'id': 48, 'name': 'Jodie Foster'}, {'id': 83, 'name': 'Anthony Hopkins'}], 'studio': {'id': 10, 'name': 'Orion Pictures', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 18, 'title': "Schindler's List", 'summary': 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.', 'year': 1993, 'genres': [{'id': 5, 'name': 'History'}, {'id': 9, 'name': 'Biography'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 0, 'name': 'Steven Spielberg'}], 'actors': [{'id': 57, 'name': 'Liam Neeson'}, {'id': 73, 'name': 'Ralph Fiennes'}], 'studio': {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'}}, 
  {'id': 19, 'title': 'The Shining', 'summary': 'A family isolated in a snowbound hotel descends into madness in this Stanley Kubrick masterpiece.', 'year': 1980, 'genres': [{'id': 4, 'name': 'Horror'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 16, 'name': 'Stanley Kubrick'}], 'actors': [{'id': 11, 'name': 'Shelley Duvall'}, {'id': 64, 'name': 'Jack Nicholson'}], 'studio': {'id': 2, 'name': 'Warner Bros.', 'headquarters': 'Burbank, USA'}}, 
  {'id': 20, 'title': 'Casablanca', 'summary': 'In Casablanca, Morocco, an American expatriate meets a former lover, leading to a tense love triangle of epic proportions.', 'year': 1942, 'genres': [{'id': 2, 'name': 'Romance'}, {'id': 11, 'name': 'War'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 29, 'name': 'Michael Curtiz'}], 'actors': [{'id': 7, 'name': 'Ingrid Bergman'}, {'id': 61, 'name': 'Humphrey Bogart'}], 'studio': {'id': 2, 'name': 'Warner Bros.', 'headquarters': 'Burbank, USA'}}, 
  {'id': 21, 'title': 'Citizen Kane', 'summary': 'A reporter investigates the life of media mogul Charles Foster Kane from his rise to his mysterious death.', 'year': 1941, 'genres': [{'id': 13, 'name': 'Mystery'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 19, 'name': 'Orson Welles'}], 'actors': [{'id': 2, 'name': 'Joseph Cotten'}, {'id': 34, 'name': 'Orson Welles'}], 'studio': {'id': 11, 'name': 'RKO Radio Pictures', 'headquarters': 'New York, USA'}}, 
  {'id': 22, 'title': '12 Angry Men', 'summary': 'A jury of twelve must deliberate and reach a unanimous verdict in a murder case.', 'year': 1957, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 27, 'name': 'Sidney Lumet'}], 'actors': [{'id': 6, 'name': 'Henry Fonda'}, {'id': 25, 'name': 'Lee J. Cobb'}], 'studio': {'id': 12, 'name': 'MGM', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 23, 'title': "Singin' in the Rain", 'summary': 'Three friends make it big in silent films and must transition to talking pictures.', 'year': 1952, 'genres': [{'id': 2, 'name': 'Romance'}, {'id': 8, 'name': 'Musical'}, {'id': 10, 'name': 'Comedy'}], 'directors': [{'id': 22, 'name': 'Gene Kelly'}, {'id': 23, 'name': 'Stanley Donen'}], 'actors': [{'id': 54, 'name': 'Gene Kelly'}, {'id': 74, 'name': "Donald O'Connor"}], 'studio': {'id': 12, 'name': 'MGM', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 24, 'title': 'Vertigo', 'summary': 'A former policeman is hired to follow a mysterious woman in San Francisco and things take a dark turn.', 'year': 1958, 'genres': [{'id': 3, 'name': 'Thriller'}, {'id': 13, 'name': 'Mystery'}], 'directors': [{'id': 18, 'name': 'Alfred Hitchcock'}], 'actors': [{'id': 3, 'name': 'James Stewart'}, {'id': 12, 'name': 'Kim Novak'}], 'studio': {'id': 1, 'name': 'Paramount Pictures', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 25, 'title': 'Psycho', 'summary': 'A woman is murdered after checking into an eerie motel run by a disturbed young man.', 'year': 1960, 'genres': [{'id': 3, 'name': 'Thriller'}, {'id': 4, 'name': 'Horror'}, {'id': 13, 'name': 'Mystery'}], 'directors': [{'id': 18, 'name': 'Alfred Hitchcock'}], 'actors': [{'id': 38, 'name': 'Janet Leigh'}, {'id': 82, 'name': 'Anthony Perkins'}], 'studio': {'id': 1, 'name': 'Paramount Pictures', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 26, 'title': 'Rear Window', 'summary': 'A housebound photographer observes the lives of his neighbors from his window and suspects one of them of murder.', 'year': 1954, 'genres': [{'id': 3, 'name': 'Thriller'}, {'id': 13, 'name': 'Mystery'}], 'directors': [{'id': 18, 'name': 'Alfred Hitchcock'}], 'actors': [{'id': 3, 'name': 'James Stewart'}, {'id': 40, 'name': 'Grace Kelly'}], 'studio': {'id': 1, 'name': 'Paramount Pictures', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 27, 'title': 'Goodfellas', 'summary': 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife and his partners.', 'year': 1990, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 6, 'name': 'Martin Scorsese'}], 'actors': [{'id': 15, 'name': 'Robert De Niro'}, {'id': 17, 'name': 'Ray Liotta'}], 'studio': {'id': 4, 'name': 'Legendary Pictures', 'headquarters': 'Burbank, USA'}}, 
  {'id': 28, 'title': 'The Godfather Part II', 'summary': 'The early life and career of Vito Corleone in 1920s New York is portrayed while his youngest son Michael expands his crime empire.', 'year': 1974, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 30, 'name': 'Francis Ford Coppola'}], 'actors': [{'id': 4, 'name': 'Al Pacino'}, {'id': 15, 'name': 'Robert De Niro'}], 'studio': {'id': 1, 'name': 'Paramount Pictures', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 29, 'title': 'Apocalypse Now', 'summary': 'A captain is sent upriver to assess a mysterious commander who has disappeared.', 'year': 1979, 'genres': [{'id': 11, 'name': 'War'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 30, 'name': 'Francis Ford Coppola'}], 'actors': [{'id': 53, 'name': 'Marlon Brando'}, {'id': 85, 'name': 'Martin Sheen'}], 'studio': {'id': 4, 'name': 'Legendary Pictures', 'headquarters': 'Burbank, USA'}}, 
  {'id': 30, 'title': 'Se7en', 'summary': 'Two detectives hunt a serial killer who uses the seven deadly sins as his motives.', 'year': 1995, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 13, 'name': 'Mystery'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 3, 'name': 'David Fincher'}], 'actors': [{'id': 14, 'name': 'Morgan Freeman'}, {'id': 29, 'name': 'Brad Pitt'}], 'studio': {'id': 3, 'name': 'Miramax', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 31, 'title': 'The Usual Suspects', 'summary': 'A con artist is arrested alongside other criminals and tells the story of how they came together.', 'year': 1995, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 13, 'name': 'Mystery'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 24, 'name': 'Bryan Singer'}], 'actors': [{'id': 31, 'name': 'Kevin Spacey'}, {'id': 49, 'name': 'Gabriel Byrne'}], 'studio': {'id': 13, 'name': 'New Line Cinema', 'headquarters': 'Burbank, USA'}}, 
  {'id': 32, 'title': 'Saving Private Ryan', 'summary': 'Following the Normandy Landings, a group of men are tasked with finding and bringing home Private James Ryan.', 'year': 1998, 'genres': [{'id': 11, 'name': 'War'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 0, 'name': 'Steven Spielberg'}], 'actors': [{'id': 20, 'name': 'Tom Hanks'}, {'id': 56, 'name': 'Edward Burns'}], 'studio': {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'}}, 
  {'id': 33, 'title': 'The Green Mile', 'summary': 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape.', 'year': 1999, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 15, 'name': 'Fantasy'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 5, 'name': 'Frank Darabont'}], 'actors': [{'id': 20, 'name': 'Tom Hanks'}, {'id': 35, 'name': 'Michael Clarke Duncan'}], 'studio': {'id': 10, 'name': 'Orion Pictures', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 34, 'title': 'Dances with Wolves', 'summary': 'A Union soldier befriends a Native American tribe and is accepted into their community.', 'year': 1990, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 14, 'name': 'Western'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 35, 'name': 'Kevin Costner'}], 'actors': [{'id': 63, 'name': 'Kevin Costner'}, {'id': 79, 'name': 'Mary McDonnell'}], 'studio': {'id': 14, 'name': 'Castle Rock Entertainment', 'headquarters': 'Burbank, USA'}}, 
  {'id': 35, 'title': 'Braveheart', 'summary': 'Scottish warrior William Wallace leads his countrymen in a rebellion to free Scotland from English rule.', 'year': 1995, 'genres': [{'id': 5, 'name': 'History'}, {'id': 9, 'name': 'Biography'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 32, 'name': 'Mel Gibson'}], 'actors': [{'id': 13, 'name': 'Sophie Marceau'}, {'id': 59, 'name': 'Mel Gibson'}], 'studio': {'id': 14, 'name': 'Castle Rock Entertainment', 'headquarters': 'Burbank, USA'}}, 
  {'id': 36, 'title': 'The Departed', 'summary': 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang.', 'year': 2006, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 3, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 6, 'name': 'Martin Scorsese'}], 'actors': [{'id': 16, 'name': 'Leonardo DiCaprio'}, {'id': 22, 'name': 'Matt Damon'}], 'studio': {'id': 4, 'name': 'Legendary Pictures', 'headquarters': 'Burbank, USA'}}, 
  {'id': 37, 'title': 'Gladiator II', 'summary': "Years after witnessing his father's death, Lucius faces his past when confronted by new powerful forces.", 'year': 2024, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 12, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 28, 'name': 'Ridley Scott'}], 'actors': [{'id': 44, 'name': 'Paul Mescal'}, {'id': 75, 'name': 'Pedro Pascal'}], 'studio': {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'}}, 
  {'id': 38, 'title': 'Oppenheimer', 'summary': 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.', 'year': 2023, 'genres': [{'id': 5, 'name': 'History'}, {'id': 9, 'name': 'Biography'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 15, 'name': 'Christopher Nolan'}], 'actors': [{'id': 36, 'name': 'Robert Downey Jr.'}, {'id': 58, 'name': 'Cillian Murphy'}], 'studio': {'id': 2, 'name': 'Warner Bros.', 'headquarters': 'Burbank, USA'}}, 
  {'id': 39, 'title': 'Barbie', 'summary': "Barbie's perfect life in the Barbie universe is interrupted when she gets a chance to experience the real world.", 'year': 2023, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 10, 'name': 'Comedy'}, {'id': 15, 'name': 'Fantasy'}], 'directors': [{'id': 25, 'name': 'Greta Gerwig'}], 'actors': [{'id': 27, 'name': 'Margot Robbie'}, {'id': 45, 'name': 'Ryan Gosling'}], 'studio': {'id': 7, 'name': 'Dreamworks Pictures', 'headquarters': 'Glendale, USA'}}, 
  {'id': 40, 'title': 'Killers of the Flower Moon', 'summary': 'Oil brings riches and violence to the Osage Nation, when a series of murders plagues the community.', 'year': 2023, 'genres': [{'id': 1, 'name': 'Crime'}, {'id': 5, 'name': 'History'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 6, 'name': 'Martin Scorsese'}], 'actors': [{'id': 15, 'name': 'Robert De Niro'}, {'id': 16, 'name': 'Leonardo DiCaprio'}], 'studio': {'id': 4, 'name': 'Legendary Pictures', 'headquarters': 'Burbank, USA'}}, 
  {'id': 41, 'title': 'The Brutalist', 'summary': 'The story of a visionary architect as he rebuilds his life and designs a monumental structure.', 'year': 2023, 'genres': [{'id': 9, 'name': 'Biography'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 12, 'name': 'Brady Corbet'}], 'actors': [{'id': 24, 'name': 'Adrien Brody'}, {'id': 84, 'name': 'Guy Pearce'}], 'studio': {'id': 18, 'name': 'A24', 'headquarters': 'New York, USA'}}, 
  {'id': 42, 'title': 'Dune', 'summary': 'Paul Atreides travels to the dangerous planet Arrakis to ensure the future of his family and people.', 'year': 2021, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 12, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 31, 'name': 'Denis Villeneuve'}], 'actors': [{'id': 19, 'name': 'Timothée Chalamet'}, {'id': 23, 'name': 'Zendaya'}], 'studio': {'id': 2, 'name': 'Warner Bros.', 'headquarters': 'Burbank, USA'}}, 
  {'id': 43, 'title': 'Dune: Part Two', 'summary': 'Paul Atreides must travel to the dangerous planet Arrakis to teach the Fremen the ways of fighting Harkonnen oppressors.', 'year': 2024, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 12, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 31, 'name': 'Denis Villeneuve'}], 'actors': [{'id': 19, 'name': 'Timothée Chalamet'}, {'id': 23, 'name': 'Zendaya'}], 'studio': {'id': 2, 'name': 'Warner Bros.', 'headquarters': 'Burbank, USA'}}, 
  {'id': 44, 'title': 'Twisters', 'summary': 'A former storm chaser reluctantly joins forces with a new team to battle destructive tornadoes.', 'year': 2024, 'genres': [{'id': 6, 'name': 'Adventure'}, {'id': 12, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 21, 'name': 'Lee Isaac Chung'}], 'actors': [{'id': 60, 'name': 'Daisy Edgar-Jones'}, {'id': 78, 'name': 'Glen Powell'}], 'studio': {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'}}, 
  {'id': 45, 'title': 'Inside Out 2', 'summary': "Riley's emotions are joined by new feelings as she enters her teenage years and navigates new social challenges.", 'year': 2024, 'genres': [{'id': 0, 'name': 'Animation'}, {'id': 6, 'name': 'Adventure'}, {'id': 10, 'name': 'Comedy'}], 'directors': [{'id': 7, 'name': 'Kelsey Mann'}], 'actors': [{'id': 47, 'name': 'Tony Hawk'}, {'id': 76, 'name': 'Kensington Tallman'}], 'studio': {'id': 9, 'name': 'Walt Disney Animation', 'headquarters': 'Burbank, USA'}}, 
  {'id': 46, 'title': 'Deadpool & Wolverine', 'summary': 'Merc with a Mouth teams up with Wolverine for an adventure across the multiverse.', 'year': 2024, 'genres': [{'id': 7, 'name': 'Sci-Fi'}, {'id': 10, 'name': 'Comedy'}, {'id': 12, 'name': 'Action'}], 'directors': [{'id': 33, 'name': 'Shawn Levy'}], 'actors': [{'id': 50, 'name': 'Hugh Jackman'}, {'id': 68, 'name': 'Ryan Reynolds'}], 'studio': {'id': 6, 'name': 'Marvel Studios', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 47, 'title': 'A Quiet Place: Day One', 'summary': 'As New York City is invaded by alien creatures that hunt by sound, a woman struggles to find her way through the chaos.', 'year': 2024, 'genres': [{'id': 4, 'name': 'Horror'}, {'id': 7, 'name': 'Sci-Fi'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 11, 'name': 'Michael Sarnoski'}], 'actors': [{'id': 5, 'name': "Lupita Nyong'o"}, {'id': 72, 'name': 'Joseph Quinn'}], 'studio': {'id': 1, 'name': 'Paramount Pictures', 'headquarters': 'Los Angeles, USA'}}, 
  {'id': 48, 'title': 'The Sympathizer', 'summary': 'A conflicted spy navigates double life in post-war Vietnam during a pivotal era of American-Vietnamese relations.', 'year': 2024, 'genres': [{'id': 3, 'name': 'Thriller'}, {'id': 5, 'name': 'History'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 9, 'name': 'Park Chan-wook'}], 'actors': [{'id': 36, 'name': 'Robert Downey Jr.'}, {'id': 43, 'name': 'Hal Yamanouchi'}], 'studio': {'id': 15, 'name': 'Apple TV+', 'headquarters': 'Cupertino, USA'}}, 
  {'id': 49, 'title': 'Kubernetes for Dummies', 'summary': 'Documentary about container orchestration and cloud-native applications in the modern era.', 'year': 2022, 'genres': [{'id': 17, 'name': 'Documentary'}], 'directors': [{'id': 20, 'name': 'Tech Filmmaker'}], 'actors': [{'id': 51, 'name': 'Various Experts'}], 'studio': {'id': 19, 'name': 'Tech Education Inc.', 'headquarters': 'San Francisco, USA'}}, 
  {'id': 50, 'title': 'The Last Duel', 'summary': 'A knight returns from war to find his wife has accused his closest friend of rape, leading to a final duel.', 'year': 2021, 'genres': [{'id': 5, 'name': 'History'}, {'id': 18, 'name': 'Drama'}], 'directors': [{'id': 28, 'name': 'Ridley Scott'}], 'actors': [{'id': 22, 'name': 'Matt Damon'}, {'id': 55, 'name': 'Adam Driver'}], 'studio': {'id': 5, 'name': 'Universal Pictures', 'headquarters': 'Universal City, USA'}}, 
  {'id': 51, 'title': 'Nomadland', 'summary': 'A woman in her sixties loses everything in the Great Recession and decides to live as a van-dwelling nomad.', 'year': 2020, 'genres': [{'id': 18, 'name': 'Drama'}], 'directors': [{'id': 1, 'name': 'Chloé Zhao'}], 'actors': [{'id': 1, 'name': 'Frances McDormand'}], 'studio': {'id': 16, 'name': 'Searchlight Pictures', 'headquarters': 'Los Angeles, USA'}}
]

movie_data = [
  {'id': 0, 'title': 'The Shawshank Redemption', 'summary': 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'year': 1994, 'genres': ['Drama'], 'directors': ['Frank Darabont'], 'actors': ['Tim Robbins', 'Morgan Freeman'], 'studio': 'Shawshank Productions'}, 
  {'id': 1, 'title': 'The Godfather', 'summary': 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his youngest and reluctant son.', 'year': 1972, 'genres': ['Crime', 'Drama'], 'directors': ['Francis Ford Coppola'], 'actors': ['Marlon Brando', 'Al Pacino'], 'studio': 'Paramount Pictures'}, 
  {'id': 2, 'title': 'The Dark Knight', 'summary': 'When the menace known as the Joker wreaks havoc on Gotham, Batman must confront his greatest challenge.', 'year': 2008, 'genres': ['Action', 'Crime', 'Drama'], 'directors': ['Christopher Nolan'], 'actors': ['Christian Bale', 'Heath Ledger'], 'studio': 'Warner Bros.'}, 
  {'id': 3, 'title': 'Pulp Fiction', 'summary': "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", 'year': 1994, 'genres': ['Crime', 'Drama'], 'directors': ['Quentin Tarantino'], 'actors': ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman'], 'studio': 'Miramax'}, 
  {'id': 4, 'title': 'Forrest Gump', 'summary': 'The presidencies of Kennedy and Johnson, the Vietnam War, and the Watergate scandal unfold from the perspective of an Alabama man with an IQ of 75.', 'year': 1994, 'genres': ['Drama', 'Romance'], 'directors': ['Robert Zemeckis'], 'actors': ['Tom Hanks', 'Sally Field'], 'studio': 'Paramount Pictures'}, 
  {'id': 5, 'title': 'Inception', 'summary': 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.', 'year': 2010, 'genres': ['Action', 'Sci-Fi', 'Thriller'], 'directors': ['Christopher Nolan'], 'actors': ['Leonardo DiCaprio', 'Marion Cotillard'], 'studio': 'Warner Bros.'}, 
  {'id': 6, 'title': 'The Matrix', 'summary': 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 'year': 1999, 'genres': ['Action', 'Sci-Fi'], 'directors': ['Lana Wachowski', 'Lilly Wachowski'], 'actors': ['Keanu Reeves', 'Laurence Fishburne'], 'studio': 'Warner Bros.'}, 
  {'id': 7, 'title': 'Interstellar', 'summary': "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", 'year': 2014, 'genres': ['Adventure', 'Drama', 'Sci-Fi'], 'directors': ['Christopher Nolan'], 'actors': ['Matthew McConaughey', 'Anne Hathaway'], 'studio': 'Paramount Pictures'}, 
  {'id': 8, 'title': 'The Avengers', 'summary': "Earth's mightiest heroes must come together and learn to fight as a team to prevent an alien invasion.", 'year': 2012, 'genres': ['Action', 'Adventure', 'Sci-Fi'], 'directors': ['Joss Whedon'], 'actors': ['Robert Downey Jr.', 'Chris Evans'], 'studio': 'Marvel Studios'}, 
  {'id': 9, 'title': 'Gladiator', 'summary': 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 'year': 2000, 'genres': ['Action', 'Adventure', 'Drama'], 'directors': ['Ridley Scott'], 'actors': ['Russell Crowe', 'Joaquin Phoenix'], 'studio': 'Universal Pictures'}, 
  {'id': 10, 'title': 'Titanic', 'summary': 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', 'year': 1997, 'genres': ['Drama', 'Romance'], 'directors': ['James Cameron'], 'actors': ['Leonardo DiCaprio', 'Kate Winslet'], 'studio': '20th Century Studios'}, 
  {'id': 11, 'title': 'Avatar', 'summary': 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.', 'year': 2009, 'genres': ['Action', 'Adventure', 'Fantasy'], 'directors': ['James Cameron'], 'actors': ['Sam Worthington', 'Zoe Saldana'], 'studio': '20th Century Studios'}, 
  {'id': 12, 'title': 'The Lion King', 'summary': 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 'year': 1994, 'genres': ['Animation', 'Adventure', 'Drama'], 'directors': ['Roger Allers', 'Rob Minkoff'], 'actors': ['James Earl Jones', 'Jeremy Irons'], 'studio': 'Walt Disney Animation'}, 
  {'id': 13, 'title': 'Jurassic Park', 'summary': 'A pragmatic paleontologist tours an almost complete theme park is tasked with protecting a couple of kids.', 'year': 1993, 'genres': ['Action', 'Adventure', 'Sci-Fi'], 'directors': ['Steven Spielberg'], 'actors': ['Sam Neill', 'Laura Dern'], 'studio': 'Universal Pictures'}, 
  {'id': 14, 'title': 'Back to the Future', 'summary': 'A teenager is accidentally sent back in time in a time-traveling car invented by an eccentric scientist, and must ensure his parents fall in love.', 'year': 1985, 'genres': ['Adventure', 'Comedy', 'Sci-Fi'], 'directors': ['Robert Zemeckis'], 'actors': ['Michael J. Fox', 'Christopher Lloyd'], 'studio': 'Universal Pictures'}, 
  {'id': 15, 'title': 'Jaws', 'summary': 'When a huge shark begins terror on the beach, the police chief, an oceanographer, and a grizzled shark hunter embark on a mission to stop it.', 'year': 1975, 'genres': ['Adventure', 'Thriller'], 'directors': ['Steven Spielberg'], 'actors': ['Roy Scheider', 'Robert Shaw'], 'studio': 'Universal Pictures'}, 
  {'id': 16, 'title': 'E.T. the Extra-Terrestrial', 'summary': 'A troubled child summons the courage to help a friendly alien escape Earth and return to his home planet.', 'year': 1982, 'genres': ['Adventure', 'Family', 'Sci-Fi'], 'directors': ['Steven Spielberg'], 'actors': ['Henry Thomas', 'Drew Barrymore'], 'studio': 'Universal Pictures'}, 
  {'id': 17, 'title': 'The Silence of the Lambs', 'summary': 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.', 'year': 1991, 'genres': ['Crime', 'Drama', 'Thriller'], 'directors': ['Jonathan Demme'], 'actors': ['Jodie Foster', 'Anthony Hopkins'], 'studio': 'Orion Pictures'}, 
  {'id': 18, 'title': "Schindler's List", 'summary': 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.', 'year': 1993, 'genres': ['Biography', 'Drama', 'History'], 'directors': ['Steven Spielberg'], 'actors': ['Liam Neeson', 'Ralph Fiennes'], 'studio': 'Universal Pictures'}, 
  {'id': 19, 'title': 'The Shining', 'summary': 'A family isolated in a snowbound hotel descends into madness in this Stanley Kubrick masterpiece.', 'year': 1980, 'genres': ['Drama', 'Horror'], 'directors': ['Stanley Kubrick'], 'actors': ['Jack Nicholson', 'Shelley Duvall'], 'studio': 'Warner Bros.'}, 
  {'id': 20, 'title': 'Casablanca', 'summary': 'In Casablanca, Morocco, an American expatriate meets a former lover, leading to a tense love triangle of epic proportions.', 'year': 1942, 'genres': ['Drama', 'Romance', 'War'], 'directors': ['Michael Curtiz'], 'actors': ['Humphrey Bogart', 'Ingrid Bergman'], 'studio': 'Warner Bros.'}, 
  {'id': 21, 'title': 'Citizen Kane', 'summary': 'A reporter investigates the life of media mogul Charles Foster Kane from his rise to his mysterious death.', 'year': 1941, 'genres': ['Drama', 'Mystery'], 'directors': ['Orson Welles'], 'actors': ['Orson Welles', 'Joseph Cotten'], 'studio': 'RKO Radio Pictures'}, 
  {'id': 22, 'title': '12 Angry Men', 'summary': 'A jury of twelve must deliberate and reach a unanimous verdict in a murder case.', 'year': 1957, 'genres': ['Crime', 'Drama'], 'directors': ['Sidney Lumet'], 'actors': ['Henry Fonda', 'Lee J. Cobb'], 'studio': 'MGM'}, 
  {'id': 23, 'title': "Singin' in the Rain", 'summary': 'Three friends make it big in silent films and must transition to talking pictures.', 'year': 1952, 'genres': ['Comedy', 'Musical', 'Romance'], 'directors': ['Gene Kelly', 'Stanley Donen'], 'actors': ['Gene Kelly', "Donald O'Connor"], 'studio': 'MGM'}, 
  {'id': 24, 'title': 'Vertigo', 'summary': 'A former policeman is hired to follow a mysterious woman in San Francisco and things take a dark turn.', 'year': 1958, 'genres': ['Mystery', 'Thriller'], 'directors': ['Alfred Hitchcock'], 'actors': ['James Stewart', 'Kim Novak'], 'studio': 'Paramount Pictures'}, 
  {'id': 25, 'title': 'Psycho', 'summary': 'A woman is murdered after checking into an eerie motel run by a disturbed young man.', 'year': 1960, 'genres': ['Horror', 'Mystery', 'Thriller'], 'directors': ['Alfred Hitchcock'], 'actors': ['Anthony Perkins', 'Janet Leigh'], 'studio': 'Paramount Pictures'}, 
  {'id': 26, 'title': 'Rear Window', 'summary': 'A housebound photographer observes the lives of his neighbors from his window and suspects one of them of murder.', 'year': 1954, 'genres': ['Mystery', 'Thriller'], 'directors': ['Alfred Hitchcock'], 'actors': ['James Stewart', 'Grace Kelly'], 'studio': 'Paramount Pictures'}, 
  {'id': 27, 'title': 'Goodfellas', 'summary': 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife and his partners.', 'year': 1990, 'genres': ['Crime', 'Drama'], 'directors': ['Martin Scorsese'], 'actors': ['Ray Liotta', 'Robert De Niro'], 'studio': 'Legendary Pictures'}, 
  {'id': 28, 'title': 'The Godfather Part II', 'summary': 'The early life and career of Vito Corleone in 1920s New York is portrayed while his youngest son Michael expands his crime empire.', 'year': 1974, 'genres': ['Crime', 'Drama'], 'directors': ['Francis Ford Coppola'], 'actors': ['Al Pacino', 'Robert De Niro'], 'studio': 'Paramount Pictures'}, 
  {'id': 29, 'title': 'Apocalypse Now', 'summary': 'A captain is sent upriver to assess a mysterious commander who has disappeared.', 'year': 1979, 'genres': ['Drama', 'War'], 'directors': ['Francis Ford Coppola'], 'actors': ['Martin Sheen', 'Marlon Brando'], 'studio': 'Legendary Pictures'}, 
  {'id': 30, 'title': 'Se7en', 'summary': 'Two detectives hunt a serial killer who uses the seven deadly sins as his motives.', 'year': 1995, 'genres': ['Crime', 'Drama', 'Mystery'], 'directors': ['David Fincher'], 'actors': ['Brad Pitt', 'Morgan Freeman'], 'studio': 'Miramax'}, 
  {'id': 31, 'title': 'The Usual Suspects', 'summary': 'A con artist is arrested alongside other criminals and tells the story of how they came together.', 'year': 1995, 'genres': ['Crime', 'Drama', 'Mystery'], 'directors': ['Bryan Singer'], 'actors': ['Gabriel Byrne', 'Kevin Spacey'], 'studio': 'New Line Cinema'}, 
  {'id': 32, 'title': 'Saving Private Ryan', 'summary': 'Following the Normandy Landings, a group of men are tasked with finding and bringing home Private James Ryan.', 'year': 1998, 'genres': ['Drama', 'War'], 'directors': ['Steven Spielberg'], 'actors': ['Tom Hanks', 'Edward Burns'], 'studio': 'Universal Pictures'}, 
  {'id': 33, 'title': 'The Green Mile', 'summary': 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape.', 'year': 1999, 'genres': ['Crime', 'Drama', 'Fantasy'], 'directors': ['Frank Darabont'], 'actors': ['Tom Hanks', 'Michael Clarke Duncan'], 'studio': 'Orion Pictures'}, 
  {'id': 34, 'title': 'Dances with Wolves', 'summary': 'A Union soldier befriends a Native American tribe and is accepted into their community.', 'year': 1990, 'genres': ['Adventure', 'Drama', 'Western'], 'directors': ['Kevin Costner'], 'actors': ['Kevin Costner', 'Mary McDonnell'], 'studio': 'Castle Rock Entertainment'}, 
  {'id': 35, 'title': 'Braveheart', 'summary': 'Scottish warrior William Wallace leads his countrymen in a rebellion to free Scotland from English rule.', 'year': 1995, 'genres': ['Biography', 'Drama', 'History'], 'directors': ['Mel Gibson'], 'actors': ['Mel Gibson', 'Sophie Marceau'], 'studio': 'Castle Rock Entertainment'}, 
  {'id': 36, 'title': 'The Departed', 'summary': 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang.', 'year': 2006, 'genres': ['Crime', 'Drama', 'Thriller'], 'directors': ['Martin Scorsese'], 'actors': ['Leonardo DiCaprio', 'Matt Damon'], 'studio': 'Legendary Pictures'}, 
  {'id': 37, 'title': 'Gladiator II', 'summary': "Years after witnessing his father's death, Lucius faces his past when confronted by new powerful forces.", 'year': 2024, 'genres': ['Action', 'Adventure', 'Drama'], 'directors': ['Ridley Scott'], 'actors': ['Paul Mescal', 'Pedro Pascal'], 'studio': 'Universal Pictures'}, 
  {'id': 38, 'title': 'Oppenheimer', 'summary': 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.', 'year': 2023, 'genres': ['Biography', 'Drama', 'History'], 'directors': ['Christopher Nolan'], 'actors': ['Cillian Murphy', 'Robert Downey Jr.'], 'studio': 'Warner Bros.'}, 
  {'id': 39, 'title': 'Barbie', 'summary': "Barbie's perfect life in the Barbie universe is interrupted when she gets a chance to experience the real world.", 'year': 2023, 'genres': ['Adventure', 'Comedy', 'Fantasy'], 'directors': ['Greta Gerwig'], 'actors': ['Margot Robbie', 'Ryan Gosling'], 'studio': 'Dreamworks Pictures'}, 
  {'id': 40, 'title': 'Killers of the Flower Moon', 'summary': 'Oil brings riches and violence to the Osage Nation, when a series of murders plagues the community.', 'year': 2023, 'genres': ['Crime', 'Drama', 'History'], 'directors': ['Martin Scorsese'], 'actors': ['Leonardo DiCaprio', 'Robert De Niro'], 'studio': 'Legendary Pictures'}, 
  {'id': 41, 'title': 'The Brutalist', 'summary': 'The story of a visionary architect as he rebuilds his life and designs a monumental structure.', 'year': 2023, 'genres': ['Biography', 'Drama'], 'directors': ['Brady Corbet'], 'actors': ['Adrien Brody', 'Guy Pearce'], 'studio': 'A24'}, 
  {'id': 42, 'title': 'Dune', 'summary': 'Paul Atreides travels to the dangerous planet Arrakis to ensure the future of his family and people.', 'year': 2021, 'genres': ['Action', 'Adventure', 'Drama'], 'directors': ['Denis Villeneuve'], 'actors': ['Timothée Chalamet', 'Zendaya'], 'studio': 'Warner Bros.'}, 
  {'id': 43, 'title': 'Dune: Part Two', 'summary': 'Paul Atreides must travel to the dangerous planet Arrakis to teach the Fremen the ways of fighting Harkonnen oppressors.', 'year': 2024, 'genres': ['Action', 'Adventure', 'Drama'], 'directors': ['Denis Villeneuve'], 'actors': ['Timothée Chalamet', 'Zendaya'], 'studio': 'Warner Bros.'}, 
  {'id': 44, 'title': 'Twisters', 'summary': 'A former storm chaser reluctantly joins forces with a new team to battle destructive tornadoes.', 'year': 2024, 'genres': ['Action', 'Adventure', 'Drama'], 'directors': ['Lee Isaac Chung'], 'actors': ['Daisy Edgar-Jones', 'Glen Powell'], 'studio': 'Universal Pictures'}, 
  {'id': 45, 'title': 'Inside Out 2', 'summary': "Riley's emotions are joined by new feelings as she enters her teenage years and navigates new social challenges.", 'year': 2024, 'genres': ['Animation', 'Adventure', 'Comedy'], 'directors': ['Kelsey Mann'], 'actors': ['Kensington Tallman', 'Tony Hawk'], 'studio': 'Walt Disney Animation'}, 
  {'id': 46, 'title': 'Deadpool & Wolverine', 'summary': 'Merc with a Mouth teams up with Wolverine for an adventure across the multiverse.', 'year': 2024, 'genres': ['Action', 'Comedy', 'Sci-Fi'], 'directors': ['Shawn Levy'], 'actors': ['Ryan Reynolds', 'Hugh Jackman'], 'studio': 'Marvel Studios'}, 
  {'id': 47, 'title': 'A Quiet Place: Day One', 'summary': 'As New York City is invaded by alien creatures that hunt by sound, a woman struggles to find her way through the chaos.', 'year': 2024, 'genres': ['Drama', 'Horror', 'Sci-Fi'], 'directors': ['Michael Sarnoski'], 'actors': ["Lupita Nyong'o", 'Joseph Quinn'], 'studio': 'Paramount Pictures'}, 
  {'id': 48, 'title': 'The Sympathizer', 'summary': 'A conflicted spy navigates double life in post-war Vietnam during a pivotal era of American-Vietnamese relations.', 'year': 2024, 'genres': ['Drama', 'History', 'Thriller'], 'directors': ['Park Chan-wook'], 'actors': ['Hal Yamanouchi', 'Robert Downey Jr.'], 'studio': 'Apple TV+'}, 
  {'id': 49, 'title': 'Kubernetes for Dummies', 'summary': 'Documentary about container orchestration and cloud-native applications in the modern era.', 'year': 2022, 'genres': ['Documentary'], 'directors': ['Tech Filmmaker'], 'actors': ['Various Experts'], 'studio': 'Tech Education Inc.'}, 
  {'id': 50, 'title': 'The Last Duel', 'summary': 'A knight returns from war to find his wife has accused his closest friend of rape, leading to a final duel.', 'year': 2021, 'genres': ['Drama', 'History'], 'directors': ['Ridley Scott'], 'actors': ['Matt Damon', 'Adam Driver'], 'studio': 'Universal Pictures'}, 
  {'id': 51, 'title': 'Nomadland', 'summary': 'A woman in her sixties loses everything in the Great Recession and decides to live as a van-dwelling nomad.', 'year': 2020, 'genres': ['Drama'], 'directors': ['Chloé Zhao'], 'actors': ['Frances McDormand'], 'studio': 'Searchlight Pictures'}
]
